export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const UPDATE_POSTS = 'UPDATE_POSTS';
export const SET_INITIAL_POSTS = 'SET_INITIAL_POSTS';
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const SET_POST_DATA = 'SET_POST_DATA';
export const SET_INITIAL_POST_DATA = 'SET_INITIAL_POST_DATA';
export const CHANGE_PAGE = 'CHANGE_PAGE';
